name: Build MPC-BE Windows x64 Zip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Prepare MSYS
        run: |
          curl -sSL https://github.com/Aleksoid1978/MSYS/raw/main/MSYS_MinGW-w64_GCC_1521_x86-x64.7z -o MSYS.7z
          7z x MSYS.7z -oC:\\MSYS
          echo '@ECHO OFF' > environments.bat
          echo 'SET "MPCBE_MSYS=C:\\MSYS"' >> environments.bat
          echo 'SET "MPCBE_MINGW=C:\\MSYS\\mingw"' >> environments.bat
          .\\update_gcc.bat
        shell: pwsh

      - name: Clean
        run: |
          .\\build.bat Clean x64 All
        shell: pwsh

      - name: Build MPC-BE x64 Zip
        run: |
          .\\build.bat Build x64 Release Zip
        shell: pwsh

      - name: Upload Zip x64
        uses: actions/upload-artifact@v4
        with:
          name: "Zip x64"
          path: _bin/Packages/**/MPC-BE*.x64.7z
          compression-level: 0
